# Generated by Django 3.2.3 on 2021-06-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='soloparaquesevea',
            fields=[
                ('Id_hola', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
