# Generated by Django 3.2.3 on 2021-06-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0002_soloparaquesevea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autos',
            name='Id_admin',
        ),
        migrations.RemoveField(
            model_name='autos',
            name='Id_color',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Id_color',
        ),
        migrations.DeleteModel(
            name='soloparaquesevea',
        ),
        migrations.DeleteModel(
            name='administrador',
        ),
        migrations.DeleteModel(
            name='autos',
        ),
        migrations.DeleteModel(
            name='personas',
        ),
        migrations.DeleteModel(
            name='sistema',
        ),
    ]
